name: Generate music.json

on:
  push:
    paths:
      - 'Music/*.mp3'
      - '.github/workflows/generate-music-json.yml'

jobs:
  generate-json:
    runs-on: ubuntu-latest
    
    steps:
    # Étape 1 : Vérifier le dépôt
    - name: Checkout code
      uses: actions/checkout@v2

    # Étape 2 : Installer FFmpeg
    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    # Étape 3 : Exécuter le script pour générer music.json
    - name: Generate music.json
      run: |
        node generate-music-json.js
